[package]
name = "cycle_counter"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]



[dependencies]
rust-libcore = "*"
kernel = { path = "../kernel" }

[build-dependencies]
gcc = "0.3"

