[package]
name = "crypto"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]

build = "buildm4.rs"

[dependencies]
rust-libcore = "*"

[build-dependencies]
gcc = "0.3"
